### ISSUE TITLE
R6: Aplicaciones no validas

### ISSUE THREAD

**Issue by cgpcsjcmp** [cgpcsjcmp/D07-Cuatrimestre-2#12]
Actualmente se pueden aplicar viajes ya comenzados. Checkear todos los casos.

**Comment by cgpcsjcmp** [comment]
Cancelados...

**Comment by cgpcsjcmp** [comment]
Se debe poder aplicar 1 vez por trip unicamente. Acualmente supuestamente funciona.

**Comment by javierelena94** [comment]
![hasapplied](https://user-images.githubusercontent.com/25828133/36949604-e782f498-1fea-11e8-9e50-9fb0a0961f6d.png)

**Comment by javierelena94** [comment]
![hasexploredapplied](https://user-images.githubusercontent.com/25828133/36989531-42a7f0a0-20a2-11e8-97e1-85bb1cade06c.png)
