### ISSUE TITLE
R9: Las tarjetas de credito no se están creando bien.

### ISSUE THREAD

**Issue by cgpcsjcmp** [cgpcsjcmp/D07-Cuatrimestre-2#13]

**Comment by alfredocampos96** [comment]
Puedes crear una tarjeta de credito con una fecha anterior a la fecha actual

**Comment by cgpcsjcmp** [comment]
![alfredo](https://user-images.githubusercontent.com/28202280/36947587-91107a34-1fce-11e8-808c-9d390af64289.JPG)

**Comment by alfredocampos96** [comment]
Esta foto no es, en el metodo save de CreditCardService hay que poner un Assert.isTrue() con que la fecha actual tiene que ser anterior a la fecha de expiracion de la tarjeta de credito
