### ISSUE TITLE
FIX: BASE DE DATOS

### ISSUE THREAD

**Issue by cgpcsjcmp** [cgpcsjcmp/D07-Cuatrimestre-2#14]
Revisar PopulateDatabase.xml entero con todas las relaciones

**Comment by cgpcsjcmp** [comment]
Los trips no se corresponden los precios con los stages. Colocar por lo menos en los del list trip correctamente (Precio trip = sumatorio(stages)*1.21)

**Comment by javierelena94** [comment]
![price1](https://user-images.githubusercontent.com/25828133/36950861-99323cd8-1ffc-11e8-8fff-9c73a35e92c0.png)

**Comment by javierelena94** [comment]
![price1](https://user-images.githubusercontent.com/25828133/36950884-e9b20be8-1ffc-11e8-9ae9-41bbe4e66098.png)

**Comment by javierelena94** [comment]
![price1](https://user-images.githubusercontent.com/25828133/36950907-1d338ea6-1ffd-11e8-9812-da05c917350c.png)

**Comment by javierelena94** [comment]
![price1](https://user-images.githubusercontent.com/25828133/36950930-59d54f20-1ffd-11e8-9075-aaf5a4e61753.png)

**Comment by javierelena94** [comment]
![price1](https://user-images.githubusercontent.com/25828133/36950948-973686cc-1ffd-11e8-9483-ea57f6001dee.png)

**Comment by javierelena94** [comment]
![price1](https://user-images.githubusercontent.com/25828133/36950957-bba77cdc-1ffd-11e8-8ca4-63eb5df86181.png)

**Comment by cgpcsjcmp** [comment]
Revisar relacion Manager-Trip que esten bien colocadas.

**Comment by cgpcsjcmp** [comment]
Eliminar todas las aplicaciones de trips no publicados.

**Comment by cgpcsjcmp** [comment]
Colocar las fechas futuras en un futuro mayor. Respetando trips publicados para qeu peudan ser cancelados y otros para que no.

**Comment by cgpcsjcmp** [comment]
de los 6 trips--->
4 publicados de los cuales 1 cancelado y otro con la fecha de comienzo pasada.
2 sin publicar SIN APLICACIONES.

**Comment by javierelena94** [comment]
PopulateDatabase.xml subido al repositorio GitHub.

**Comment by javierelena94** [comment]
![hasexploredapplied](https://user-images.githubusercontent.com/25828133/36989434-0903484a-20a2-11e8-9569-bf1e77d45a9e.png)
