### ISSUE TITLE
Al borrar un Trip, también debe eliminarse de la base de datos.

### ISSUE THREAD

**Issue by javierelena94** [cgpcsjcmp/D07-Cuatrimestre-2#19]

**Comment by javierelena94** [comment]
Es necesario que se haga entre todos y se discuta de nuevo las relaciones.
¿Trip debe tener como atributo sponsorships si se cogen estos al azar para ponerlo en la vista de display trip?

Hay que borrar todas las relaciones que tenga ese trip.

**Comment by cgpcsjcmp** [comment]
RANGER TAG????

**Comment by cgpcsjcmp** [comment]
![trip service](https://user-images.githubusercontent.com/28202280/36983721-6ac7e3f6-2093-11e8-9bd1-21ce48c94274.PNG)
![auditservice](https://user-images.githubusercontent.com/28202280/36983733-6f4b3716-2093-11e8-88ce-7312acadbf64.PNG)
![sponsorshipservice](https://user-images.githubusercontent.com/28202280/36983743-735ce034-2093-11e8-94f7-bfb0af193a26.PNG)
![sponsorservvice](https://user-images.githubusercontent.com/28202280/36983745-75f56118-2093-11e8-8e30-373018518ca7.PNG)
![sponsorrepository](https://user-images.githubusercontent.com/28202280/36983748-79ca87b4-2093-11e8-88ab-d51685638e2d.PNG)

**Comment by cgpcsjcmp** [comment]
Movidas notes de los trips no publicados al trip 1 y 2
