### ISSUE TITLE
Indicar que si un Trip no se borra es porque ha pasado su fecha de publicación.

### ISSUE THREAD

**Issue by javierelena94** [cgpcsjcmp/D07-Cuatrimestre-2#20]

**Comment by cgpcsjcmp** [comment]
Trip manager Controller

![tripmanagercontroller](https://user-images.githubusercontent.com/28202280/36988661-b2a2124e-209f-11e8-9105-ff0debea5450.PNG)

**Comment by cgpcsjcmp** [comment]
Añadido trip.delete.error en messages.
