### ISSUE TITLE
Cancelar aplicaciones al cancelar trip.

### ISSUE THREAD

**Issue by cgpcsjcmp** [cgpcsjcmp/D07-Cuatrimestre-2#23]

**Comment by javierelena94** [comment]
![hasexploredapplied](https://user-images.githubusercontent.com/25828133/36996456-3356c224-20b7-11e8-8652-4a5d5de43487.png)

**Comment by javierelena94** [comment]
![hasexploredapplied](https://user-images.githubusercontent.com/25828133/36996609-826c8f74-20b7-11e8-9cb6-595a9c64515e.png)
