### ISSUE TITLE
R1: Al crear explorador tira Panic de assert

### ISSUE THREAD

**Issue by cgpcsjcmp** [cgpcsjcmp/D07-Cuatrimestre-2#5]
![panic r1](https://user-images.githubusercontent.com/28202280/36898341-c22e826a-1e1a-11e8-82bb-99acac0794ed.png)

**Comment by cgpcsjcmp** [comment]
![r1 panic 2](https://user-images.githubusercontent.com/28202280/36898391-fe000246-1e1a-11e8-87dd-b08e8b07d0d7.png)

**Comment by cgpcsjcmp** [comment]
![consola](https://user-images.githubusercontent.com/28202280/36898472-4208363e-1e1b-11e8-951a-dfcf118b15d8.png)

**Comment by cgpcsjcmp** [comment]
Mirar convertidores y checkear objeto pasado en el post.

**Comment by cgpcsjcmp** [comment]
Si se introduce un usuario que existe tira panic. Si se introduce uno que no existe tira panic pero lo crea.

**Comment by machirulis** [comment]
- Panic al crear ranger/explorer: alguien añadió en el save del servicio unas líneas que llamaba al LoginService, lo cual no tiene sentido. Lo he eliminado.
- Panic al crear ranger/explorer con mismo username: arreglado con añadir un try/catch que pille el fallo y no devuelva un panic.
