### ISSUE TITLE
R5: Las categorias por defecto nunca se pueden borrar

### ISSUE THREAD

**Issue by cgpcsjcmp** [cgpcsjcmp/D07-Cuatrimestre-2#8]
Revisar base de datos. Implementar el checkeo del nombre de las categorias con la variable de SystemConfig.

**Comment by machirulis** [comment]
Añadido: 
`		for (final String cName : this.systemConfigService.find().getDefaultCategories())
			if (cName.equals(category.getName()))
				return this.createEditModelAndView(category, "category.comit.error");`
en el edit que pasa por parámetro una categoryId del CategoryAdministratorController.
